<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5mkapkv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5mkapkv/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5mkapkv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5mkapkv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5mkapkv\appProdProjectContainer(array(
    'container.build_hash' => '5mkapkv',
    'container.build_id' => '9786c506',
    'container.build_time' => 1519654950,
));
