<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXytvbop\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXytvbop/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXytvbop.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXytvbop\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXytvbop\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xytvbop',
    'container.build_id' => 'e53e1a6f',
    'container.build_time' => 1523278164,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXytvbop');
